version: "3.9"
services:
  app:
    build: .
    container_name: app
    image: app
    ports:
      - 8080:8080
  integration:
    build:
      context: .
      dockerfile: integration-test/Dockerfile
    container_name: integration
    image: integration