// Code generated by MockGen. DO NOT EDIT.
// Source: ports.go

// Package raffle_test is a generated GoMock package.
package raffle_test

import (
	context "context"
	reflect "reflect"

	raffle "github.com/evmartinelli/go-rifa-microservice/internal/core/raffle"
	gomock "github.com/golang/mock/gomock"
)

// MockRepo is a mock of Repo interface.
type MockRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRepoMockRecorder
}

// MockRepoMockRecorder is the mock recorder for MockRepo.
type MockRepoMockRecorder struct {
	mock *MockRepo
}

// NewMockRepo creates a new mock instance.
func NewMockRepo(ctrl *gomock.Controller) *MockRepo {
	mock := &MockRepo{ctrl: ctrl}
	mock.recorder = &MockRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepo) EXPECT() *MockRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRepo) Create(arg0 context.Context, arg1 *raffle.Raffle) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepoMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepo)(nil).Create), arg0, arg1)
}

// GetAvailableRaffle mocks base method.
func (m *MockRepo) GetAvailableRaffle(arg0 context.Context) ([]raffle.Raffle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvailableRaffle", arg0)
	ret0, _ := ret[0].([]raffle.Raffle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvailableRaffle indicates an expected call of GetAvailableRaffle.
func (mr *MockRepoMockRecorder) GetAvailableRaffle(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvailableRaffle", reflect.TypeOf((*MockRepo)(nil).GetAvailableRaffle), arg0)
}
