// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/available/do-create": {
            "post": {
                "description": "Create a Raffle",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "raffle"
                ],
                "summary": "Create",
                "operationId": "do-create",
                "parameters": [
                    {
                        "description": "Set up raffle",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.doRaffleRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/v1.response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.response"
                        }
                    }
                }
            }
        },
        "/raffle/available": {
            "get": {
                "description": "Show all available raffles",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "raffle"
                ],
                "summary": "Show raffles",
                "operationId": "available",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.availableResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.response"
                        }
                    }
                }
            }
        },
        "/steam//do-player-inventory": {
            "post": {
                "description": "Create a Player Inventory",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "steam"
                ],
                "summary": "Create",
                "operationId": "do-player-inventory",
                "parameters": [
                    {
                        "description": "Set up raffle",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.doRaffleRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/skin.Skin"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "raffle.Raffle": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "61f0c143ad06223fa03910b0"
                },
                "name": {
                    "type": "string",
                    "example": "Rifa"
                },
                "status": {
                    "type": "string",
                    "example": "Available"
                },
                "totalNumbers": {
                    "type": "integer",
                    "example": 10
                },
                "totalSold": {
                    "type": "integer",
                    "example": 1
                },
                "value": {
                    "type": "integer",
                    "example": 5
                }
            }
        },
        "skin.Item": {
            "type": "object",
            "properties": {
                "icon_url": {
                    "type": "string"
                },
                "market_hash_name": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "skin.Skin": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/skin.Item"
                    }
                },
                "steam_id": {
                    "type": "string"
                }
            }
        },
        "v1.availableResponse": {
            "type": "object",
            "properties": {
                "available": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/raffle.Raffle"
                    }
                }
            }
        },
        "v1.doRaffleRequest": {
            "type": "object",
            "required": [
                "name",
                "totalNumbers",
                "value"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "example": "rifa faca"
                },
                "totalNumbers": {
                    "type": "integer",
                    "example": 20
                },
                "value": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "v1.response": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "message"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "Go Clean Template API",
	Description:      "Using a translation service as an example",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
