basePath: /v1
definitions:
  order.Request:
    properties:
      numbers:
        example:
        - 1
        - 2
        items:
          type: integer
        type: array
      productID:
        example: 30dd879c-ee2f-11db-8314-0800200c9a66
        type: string
    required:
    - numbers
    - productID
    type: object
  raffle.Raffle:
    properties:
      description:
        example: Rifa description
        type: string
      id:
        example: 61f0c143ad06223fa03910b0
        type: string
      imageURL:
        example: "1"
        type: string
      name:
        example: Rifa
        type: string
      quantity:
        example: 10
        type: integer
      slug:
        example: butterfly-32
        type: string
      sortedNumber:
        example: 10
        type: integer
      status:
        example: open
        type: string
      unitPrice:
        example: 5
        type: integer
      userLimit:
        example: 10
        type: integer
      variation:
        items:
          $ref: '#/definitions/raffle.Variation'
        type: array
    type: object
  raffle.Request:
    properties:
      description:
        example: Rifa
        type: string
      imageURL:
        example: "1"
        type: string
      name:
        example: Rifa
        type: string
      quantity:
        example: 10
        type: integer
      unitPrice:
        example: 5
        type: integer
    required:
    - description
    - imageURL
    - name
    - quantity
    - unitPrice
    type: object
  raffle.Variation:
    properties:
      id:
        example: 61f0c143ad06223fa03910b0
        type: string
      name:
        example: Number
        type: string
      number:
        example: 5
        type: integer
      status:
        example: paid
        type: string
    type: object
  skin.Item:
    properties:
      icon_url:
        type: string
      market_hash_name:
        type: string
      name:
        type: string
    type: object
  skin.Skin:
    properties:
      id:
        type: string
      items:
        items:
          $ref: '#/definitions/skin.Item'
        type: array
      steam_id:
        type: string
    type: object
  v1.availableResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/raffle.Raffle'
        type: array
    type: object
  v1.doSteamRequest:
    properties:
      steam_id:
        example: "894012849024820948209"
        type: string
    required:
    - steam_id
    type: object
  v1.response:
    properties:
      error:
        example: message
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Using a translation service as an example
  title: Go Clean Template API
  version: "1.0"
paths:
  /order/:
    post:
      consumes:
      - application/json
      description: Create a Order
      operationId: do-post
      parameters:
      - description: Set up order
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/order.Request'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/v1.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
      summary: Create
      tags:
      - order
  /raffle/:
    get:
      consumes:
      - application/json
      description: Show all available raffles
      operationId: getAll
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.availableResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
      summary: Show raffles
      tags:
      - raffle
    post:
      consumes:
      - application/json
      description: Create a Raffle
      operationId: do-create
      parameters:
      - description: Set up raffle
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/raffle.Request'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/v1.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
      summary: Create
      tags:
      - raffle
  /raffle/:id:
    get:
      consumes:
      - application/json
      description: Show raffle by ID
      operationId: getbyID
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.availableResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
      summary: Show raffles
      tags:
      - raffle
  /steam/do-player-inventory:
    post:
      consumes:
      - application/json
      description: Create a Player Inventory
      operationId: do-player-inventory
      parameters:
      - description: set up steam
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/v1.doSteamRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/skin.Skin'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
      summary: Create
      tags:
      - steam
swagger: "2.0"
